import {  Poppins } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const poppins = Poppins({
  subsets: ["latin"],
  weight: "400"
});

export const metadata = {
  title: "Practice Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col p-6" suppressHydrationWarning>
          <nav>
              <ul className="flex gap-5 border-gray-600 border-b mb-8">
                  <li><Link href= '/'>home</Link></li>
                  <li><Link href= '/about'>About</Link></li>
                  <li><Link href= '/blogs'>Blog</Link></li>
                  <li><Link href= '/posts'>Post</Link></li>
              </ul>
          </nav>
        {children}
      </body>
    </html>
  );
}
